services:
  
  api-gateway:
    image: openresty/openresty:alpine
    container_name: api-gateway
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./nginx/logs:/usr/local/openresty/nginx/logs
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - corebank-net
    depends_on:
      - authentication

  message_queue:
    image: apache/kafka:latest
    container_name: message_queue
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://message_queue:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@message_queue:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: ${KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS}
      KAFKA_NUM_PARTITIONS: ${KAFKA_NUM_PARTITIONS}
      KAFKA_MESSAGE_MAX_BYTES: ${KAFKA_MESSAGE_MAX_BYTES}          # 2 GB max message size
      KAFKA_REPLICA_FETCH_MAX_BYTES: ${KAFKA_REPLICA_FETCH_MAX_BYTES}    # allow replicas to fetch larger messages
      KAFKA_FETCH_MAX_BYTES: ${KAFKA_FETCH_MAX_BYTES}            # client fetch size
    networks:
      - corebank-net

  kafka-ui:
    image: obsidiandynamics/kafdrop
    container_name: kafka-ui
    environment:
      - KAFKA_BROKERCONNECT=message_queue:9092
    ports:
      - 9091:9000
    depends_on:
      - message_queue
    networks:
      - corebank-net

  authentication-db:
    image: postgres:15-alpine
    container_name: authentication-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${AUTH_USER}
      POSTGRES_PASSWORD: ${AUTH_PASS}
      POSTGRES_DB: ${AUTH_DB}
    ports:
      - 5432:5432
    volumes:
      - ./authenticationservice/auth_db:/var/lib/postgresql/data
    networks:
      - corebank-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${AUTH_USER} -d $${AUTH_DB}"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s

  authentication:
    build: 
      context: .
      dockerfile: authenticationservice/Dockerfile
    container_name: authentication-service
    restart: unless-stopped
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: message_queue:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://authentication-db:${AUTH_DB_PORT}/${AUTH_DB}
      SPRING_DATASOURCE_USERNAME: ${AUTH_USER}
      SPRING_DATASOURCE_PASSWORD: ${AUTH_PASS}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_SHOW-SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS: true
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      SECURITY_ENDPOINTS: ${PUBLIC_ENDPOINTS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CORS_ALLOWED_HEADERS: ${CORS_ALLOWED_HEADERS}
      CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS}
      CORS_ALLOWED_CREDENTIALS: ${CORS_ALLOWED_CREDENTIALS}
    depends_on: 
      authentication-db:
        condition: service_healthy
    ports:
      - 8081:8080
    networks:
      - corebank-net

volumes:
  auth_db:
    driver: local

networks:
  corebank-net:
    driver: bridge