services:
  
  api-gateway:
    image: openresty/openresty:alpine
    container_name: api-gateway
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./nginx/logs:/usr/local/openresty/nginx/logs
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - corebank-net
    depends_on:
      - authentication
      - notification
      - message_queue

  message_queue:
    image: apache/kafka:latest
    container_name: message_queue
    ports:
      - 9092:9092
    environment:
      KAFKA_HEAP_OPTS: ${KAFKA_HEAP_OPTS}
      KAFKA_NODE_ID: 1
      KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://message_queue:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@message_queue:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: ${KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS}
      KAFKA_NUM_PARTITIONS: ${KAFKA_NUM_PARTITIONS}
      KAFKA_MESSAGE_MAX_BYTES: ${KAFKA_MESSAGE_MAX_BYTES}          # 2 GB max message size
      KAFKA_REPLICA_FETCH_MAX_BYTES: ${KAFKA_REPLICA_FETCH_MAX_BYTES}    # allow replicas to fetch larger messages
      KAFKA_FETCH_MAX_BYTES: ${KAFKA_FETCH_MAX_BYTES}            # client fetch size
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: ${KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS}
      # Add authentication if needed
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
    networks:
      - corebank-net
    volumes:
      - ./message_queue/kafka:/tmp/kafka-logs
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 30s
      timeout: 10s
      retries: 3

  kafka-ui:
    image: obsidiandynamics/kafdrop
    container_name: kafka-ui
    environment:
      - KAFKA_BROKERCONNECT=message_queue:9092
    ports:
      - 9091:9000
    depends_on:
      - message_queue
    networks:
      - corebank-net

# Databases
  authentication-db:
    image: postgres:15-alpine
    container_name: authentication-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${AUTH_USER}
      POSTGRES_PASSWORD: ${AUTH_PASS}
      POSTGRES_DB: ${AUTH_DB}
    ports:
      - ${POSTGRESQL_DB_PORT}:5432
    volumes:
      - ./database/auth_db:/var/lib/postgresql/data
    networks:
      - corebank-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${AUTH_USER} -d $${AUTH_DB}"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s

  notification-db:
    image: postgres:15-alpine
    container_name: notification-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${NOTIFICATION_USER}
      POSTGRES_PASSWORD: ${NOTIFICATION_PASS}
      POSTGRES_DB: ${NOTIFICATION_DB}
    ports:
      - ${POSTGRESQL_DB_PORT}:5432
    volumes:
      - ./database/notification_db:/var/lib/postgresql/data
    networks:
      - corebank-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${NOTIFICATION_USER} -d $${NOTIFICATION_DB}"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s

  # Services
  authentication:
    build: 
      context: .
      dockerfile: authenticationservice/Dockerfile
    container_name: authentication-service
    restart: unless-stopped
    environment:
      SPRING_APPLICATION_NAME: authentication
      SPRING_KAFKA_BOOTSTRAP_SERVERS: message_queue:9092
      SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.springframework.kafka.support.serializer.JsonSerializer
      SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: org.apache.kafka.common.serialization.StringDeserializer
      SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: org.springframework.kafka.support.serializer.JsonDeserializer
      SPRING_KAFKA_CONSUMER_GROUP_ID: ${SPRING_KAFKA_CONSUMER_GROUP_ID_AUTH}
      SPRING_KAFKA_LISTENER_MISSING_TOPICS_FATAL: ${SPRING_KAFKA_LISTENER_MISSING_TOPICS_FATAL}
      SPRING_KAFKA_LISTENER_ACK_MODE: ${SPRING_KAFKA_LISTENER_ACK_MODE}
      SPRING_KAFKA_PRODUCER_ACKS: all
      SPRING_KAFKA_PRODUCER_RETRIES: 3
      SPRING_DATASOURCE_URL: jdbc:postgresql://authentication-db:${POSTGRESQL_DB_PORT}/${AUTH_DB}
      SPRING_KAFKA_PRODUCER_PROPERTIES_SPRING_JSON_ADD_TYPE_INFO_HEADERS: ${SPRING_JSON_ADD_TYPE_INFO_HEADERS}
      SPRING_DATASOURCE_USERNAME: ${AUTH_USER}
      SPRING_DATASOURCE_PASSWORD: ${AUTH_PASS}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES: ${SPRING_JSON_TRUSTED_PACKAGES}
      SPRING_JPA_SHOW-SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS: true
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      SECURITY_ENDPOINTS: ${PUBLIC_ENDPOINTS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CORS_ALLOWED_HEADERS: ${CORS_ALLOWED_HEADERS}
      CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS}
      CORS_ALLOWED_CREDENTIALS: ${CORS_ALLOWED_CREDENTIALS}
    depends_on: 
      - authentication-db
      - message_queue
    ports:
      - 8081:8080
    networks:
      - corebank-net

  notification:
    build: 
      context: .
      dockerfile: notification/Dockerfile
    container_name: notification-service
    restart: unless-stopped
    environment:
      SPRING_APPLICATION_NAME: notification
      SPRING_KAFKA_BOOTSTRAP_SERVERS: message_queue:9092
      SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: org.apache.kafka.common.serialization.StringSerializer
      SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: org.springframework.kafka.support.serializer.JsonSerializer
      SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: org.apache.kafka.common.serialization.StringDeserializer
      SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: org.springframework.kafka.support.serializer.JsonDeserializer
      SPRING_KAFKA_CONSUMER_GROUP_ID: ${SPRING_KAFKA_CONSUMER_GROUP_ID_NOTIFICATION}
      SPRING_KAFKA_LISTENER_MISSING_TOPICS_FATAL: ${SPRING_KAFKA_LISTENER_MISSING_TOPICS_FATAL}
      SPRING_KAFKA_LISTENER_ACK_MODE: ${SPRING_KAFKA_LISTENER_ACK_MODE}
      SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES: ${SPRING_JSON_TRUSTED_PACKAGES}
      SPRING_KAFKA_PRODUCER_PROPERTIES_SPRING_JSON_ADD_TYPE_INFO_HEADERS: ${SPRING_JSON_ADD_TYPE_INFO_HEADERS}
      SPRING_KAFKA_PRODUCER_ACKS: all
      SPRING_KAFKA_PRODUCER_RETRIES: 3
      SPRING_DATASOURCE_URL: jdbc:postgresql://notification-db:${POSTGRESQL_DB_PORT}/${NOTIFICATION_DB}
      SPRING_DATASOURCE_USERNAME: ${NOTIFICATION_USER}
      SPRING_DATASOURCE_PASSWORD: ${NOTIFICATION_PASS}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_SHOW-SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_USE_SQL_COMMENTS: true
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      SECURITY_ENDPOINTS: ${PUBLIC_ENDPOINTS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CORS_ALLOWED_HEADERS: ${CORS_ALLOWED_HEADERS}
      CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS}
      CORS_ALLOWED_CREDENTIALS: ${CORS_ALLOWED_CREDENTIALS}
      SPRING_MAIL_HOST: ${SMTP_MAIL_HOST}
      SPRING_MAIL_PORT: ${SMTP_MAIL_PORT}
      SPRING_MAIL_USERNAME: ${SMTP_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SMTP_MAIL_PASSWORD}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: ${SMTP_MAIL_SMTP_AUTH}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: ${SMTP_STARTTLS_ENABLE}
    ports:
      - 8082:8080
    networks:
      - corebank-net
    depends_on:
      - notification-db
      - message_queue

volumes:
  kafka:
  notification_db:
  auth_db:
    driver: local

networks:
  corebank-net:
    driver: bridge