services:
  
  api-gateway:
    image: openresty/openresty:alpine
    container_name: api-gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./nginx/logs:/usr/local/openresty/nginx/logs
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - corebank-net
    depends_on:
      - authentication

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - corebank-net

  message_queue:
    image: wurstmeister/kafka:2.13-2.8.0
    container_name: message_queue
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT//message_queue:9092 # for test we are not implementing ssl
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    depends_on: 
      - zookeeper
    networks:
      - corebank-net

  authentication-db:
    image: postgresql:15-alpine
    container_name: authentication-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${AUTH_USER}
      POSTGRES_PASSWORD: ${AUTH_PASS}
      POSTGRES_DB: ${AUTH_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./authenticationservice/auth_db:/var/lib/postgresql/data
    networks:
      - corebank-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${AUTH_USER} -d $${AUTH_DB}"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s

  authentication:
    build: ./authenticationservice
    container_name: authentication-service
    restart: unless-stopped
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: message_queue:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:${AUTH_DB_PORT}/${AUTH_DB}
      SPRING_DATASOURCE_USERNAME: ${AUTH_USER}
      SPRING_DATASOURCE_PASSWORD: ${AUTH_PASS}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_SHOW-SQL: true
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      SECURITY_ENDPOINTS: ${PUBLIC_ENDPOINTS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CORS_ALLOWED_HEADERS: ${CORS_ALLOWED_HEADERS}
      CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS}
      CORS_ALLOWED_CREDENTIALS: ${CORS_ALLOWED_CREDENTIALS}
    depends_on: 
      - authentication-db
    ports:
      - "8080:8080"
    networks:
      - corebank-net

volumes:
  auth_db:
    driver: local

networks:
  corebank-net:
    driver: bridge